Support mapped SMILES in `from_smiles` with minimal guarantees
openforcefield/openff-toolkit pull request #1482
Opened 2022-12-07 03:11 UTC by Yoshanuikabundi

This PR adds a best-effort approach to supporting mapped SMILES in the `from_smiles` method. This hopefully reduces the common "oops, I forgot `from_mapped_smiles` exists" mistake. It also adds documentation to `from_smiles` recommending the use of `from_mapped_smiles` when atom ordering is important. It carefully makes no guarantees (except in the private implementing method) about this behavior and suggests that users not rely on it. Obviously users probably will rely on it and we won't be able to change it later, but at least offering exceptions for broken maps gives people an incentive to use `from_mapped_smiles` (which is also now more discoverable).

This is not a breaking change, as the changed behavior was not previously specified.

The last commit in this PR is optional. It simplifies `from_mapped_smiles` to avoid a second call to `remap`. This modifies the exceptions raised when an invalid mapping is provided to `from_mapped_smiles` to be less specific, which may not be desirable.

Closes #1439.

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/tests)
- [x] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

2022-12-07 07:25 UTC, Yoshanuikabundi commented
Welp I guess it wasn't redundant... I'll dig into this more soon.

2022-12-08 02:01 UTC, j-wags requested changes
I'm not inclined to accept this, for a few reasons. In order of decreasing problematic-ness:

* (fundamental) behavior has "activity cliffs" - Someone could notice this behavior on a few inputs, assume it's "safe", and then get burned when working on a large dataset where some inputs aren't formatted in the way we expect. Worse, the cases where this behavior doesn't happen would be silent. It would be better in that case if the user had used `from_mapped_smiles` for all their work.
* (fixable) Partial maps work, but I don't think they should because they invite so many edge cases

There are also big upsides here, but I'm not sure how they balance out with the downsides. I'll keep thinking about this - Would be happy to get more input!

2022-12-08 03:31 UTC, Yoshanuikabundi commented
My thoughts:

*Activity cliffs:* I agree with this concern. This PR represents a trade off between two kinds of bugs in user code: 

1. molecules with atoms in the wrong order because a user assumes `from_smiles` will order their atoms according to the map
2. molecules with atoms in the wrong order because a user provides an incorrect mapping in their SMILES. 

(1) is a bug that I've written, and I know others have too. (2) is mitigated in this PR by not making guarantees to users and pointing them to `from_mapped_smiles()` in the docs, which preserves the current safe behavior (raises an exception with incomplete, ambiguous, or invalid maps). 

If we decide not to merge this PR, we should certainly merge a new PR to add a warning about the lack of mapping behavior to the `from_smiles` docstrings and pointing users to `from_mapped_smiles()` to mitigate (1).

*Partial maps*: Partial maps are really useful when you don't want a cluttered SMILES, but you need some atoms in the right spot. This is really useful for writing examples, especially in high time pressure situations. If users want protection from their erroneous input, `from_mapped_smiles()` continues to forbid partial maps, so they can use that.

I'm also unsure how this concern would be fixed without discarding this PR; we can't have `from_smiles` raise an exception on a partial map, and having the remap happen only when the map is complete and correct would be even more of an activity cliff.

2022-12-08 16:21 UTC, jthorton commented
I probably need to look into this more but I have a feeling this will break openff-fragmenter which uses partial atom maps a lot. It often makes molecules using `from_smiles` with partial maps then makes use of the `atom_map` property to track which atoms have been conserved from the parent. If this simplifies the logic in tracking the index then its not a bad break but it might need checking how this would change fragmenter.

2022-12-08 18:29 UTC, j-wags commented
Thanks for chiming in @jthorton. I think (with ~80% confidence) fragmenter would survive this - The atom map is of the form `{atom_index_in_this_molecule: map_value}`, and while this method would make a molecule with different atom ordering (remember, the atom order of a molecule read from smiles has always been arbitrary), the _keys_ of the map would reflect the new ordering, and the _values_ (which fragmenter cares about) would be unchanged.

2022-12-08 18:57 UTC, pavankum commented
From some old discussion at #1186 , I lean towards adding an optional argument `mapped=True`, otherwise it would be a burden to figure out edge cases.

2022-12-09 11:17 UTC, Yoshanuikabundi commented
@pavankum I'm not sure what edge cases we're worried about? We currently make no guarantees about atom order, and different toolkits in fact provide different orderings, so I'm not sure how this change can introduce edge cases. Or are you suggesting a `mapped` argument as an alternative to this PR?

> I think (with ~80% confidence) fragmenter would survive this

If this breaks fragmenter, then I think there's either a bug in my code or some undocumented feature of `from_smiles` that fragmenter relies on (and bug in my code seems much more likely). This PR was designed to be completely transparent/invisible to use cases that use maps for anything other than atom ordering - it'll reorder the atoms, but that's invisible because the order was previously unspecified, and the only other thing that depends on the ordering but isn't updated by `remap` is the atom map, which is updated so that the atoms all keep the right map :grin: 

In fact, I think there's an argument that the code updating the atom map should really be in `remap()` - that way the atom map remains correct after any remap, which is currently not guaranteed. At the moment, calling `remap` leaves the atom map unchanged (and therefore potentially inconsistent with the new ordering). But that's definitely a breaking change.

2022-12-12 04:07 UTC, Yoshanuikabundi commented
> from your second point here it was not clear for me whether you are going to raise exceptions similar to from_mapped_smiles, I think it would be great to do so. Otherwise, Molecule.from_smiles('[CH3:4]-[CH3:5]') is valid with from_smiles since it reassigns the indices, and fails with parsing error if we use from_mapped_smiles. Another example would be '[CH3:1]-[CH3:1]'. Although I don't anticipate that anyone would sail through without a failure somewhere downstream if they assign and use garbage indices like these.

`from_smiles` is intended to never raise an exception from a bad atom map. This is an important feature of the current implementation that we can't really change for two reasons - firstly, it would be a breaking change and it missed the train for breaking changes for the next little while, and secondly because atom ordering is not the only use case for atom maps. A user might want to assign different atoms the same map, or assign non-consecutive maps, or partial maps, or even assign maps that are out-of-range of the molecule, and we should support that. At present we do that by storing the atom map in the molecule's properties, and allowing the user to use it for remapping or whatever else they like. The only change here is that the common use case of atom ordering is handled automatically where the behavior was previously unspecified. If users need us to ensure their indices are correct, they still need to use `from_mapped_smiles`, this PR just provides a soft landing if they don't read the docs and don't see that method.

> Apologies, I misread your PR as adding a way to parse mapped smiles through from_smiles, but I see that you are handling partial maps as well, which is a great feature.

No worries :grin: Just to be clear, in this PR we only support partial maps in `from_smiles` - `from_mapped_smiles` continues to require a complete map. We could conceivably add a `allow_partial` argument to `from_mapped_smiles` or something (but probably not in this PR).

2022-12-13 04:11 UTC, pavankum commented
@Yoshanuikabundi Thanks for the clarifications!

2022-12-22 01:59 UTC, j-wags commented
Upon some more careful reflection, I'm still really uncomfortable about introducing this behavior. I'm going to close this PR for now, but if folks on the science team really want this feel free to restart the conversation.

2022-12-22 01:59 UTC, closed without merging