Use pytest 8 in CI
openforcefield/openff-toolkit pull request #1822
Opened 2024-02-05 17:17 UTC by mattwthompson

- [ ] Tag issue being addressed
- [ ] Add [tests](https://github.com/openforcefield/openff-toolkit/tree/main/openff/toolkit/_tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openff-toolkit/tree/main/docs), if applicable
- [ ] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openff-toolkit/blob/main/docs/releasehistory.rst)

2024-02-06 14:25 UTC, mattwthompson commented
Ha, I've gotten this error before but in a position where it didn't need to be fixed

```
=========================== short test summary info ============================
FAILED openff/toolkit/_tests/test_forcefield.py::TestForceField::test_load_bad_filelike_object - TypeError: argument of type 'NoneType' is not iterable
FAILED openff/toolkit/_tests/test_forcefield.py::TestForceField::test_do_not_load_in_child_dir - TypeError: argument of type 'NoneType' is not iterable
FAILED openff/toolkit/_tests/test_forcefield.py::TestForceField::test_load_bad_bytes - TypeError: argument of type 'NoneType' is not iterable
FAILED openff/toolkit/_tests/test_forcefield.py::TestForceField::test_load_bad_string - TypeError: argument of type 'NoneType' is not iterable

2024-02-15 17:34 UTC, mattwthompson commented
Splitting off some more discrete ideas which might be nice to have in the installed package before this works nicely, starting with

* #1825

2025-01-16 20:50 UTC, j-wags requested changes
Thanks, this was clearly a ton of work all over the codebase and I really appreciate you hunting it all down. However in the current state I can't tell what's a temporary patch to get CI passing vs. what would actually be committed. Now that I see the green CI on this PR, could you modify it to be in its final state and update the PR text with any major subsequent steps that you'd plan to take after the review (otherwise I can't tell what's a temporary patch vs. a genuine oversight).

2025-01-16 20:50 UTC, j-wags commented on .github/workflows/conda.yml
> +            pytest-rerunfailures
(blocking) Could you expand on the reasoning for not putting these in `conda_oe.yaml`? Especially with version pins this seems like something that may confuse us in the future. If these are outside of that file intentionally, it'd be good to leave a comment explaining why.

2025-01-16 20:50 UTC, j-wags commented on .github/workflows/conda.yml
> -          git log -1 | cat
(blocking) This line seems essential to ensuring that the last release is being tested against its own tests, rather than the tests currently on `main`. Could you clarify?

2025-01-17 20:02 UTC, mattwthompson commented on .github/workflows/conda.yml
> +            smirnoff-plugins=2024
Can take it or leave it

2025-01-17 20:05 UTC, mattwthompson commented on .github/workflows/conda.yml
> +            pytest-rerunfailures
I wanted to drop that file but instead I'm just reverting all of the "conda" tests

2025-01-17 20:05 UTC, mattwthompson commented on .github/workflows/conda.yml
> -          git log -1 | cat
As above

2025-01-21 16:59 UTC, j-wags approved these changes
Awesome, thanks for all the hard work and for iterating on this @mattwthompson. Please update the releasenotes before you merge!

2025-01-21 21:56 UTC, merged